basePath: /
definitions:
  blog.Blog:
    properties:
      author:
        type: string
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
host: localhost:8001
info:
  contact: {}
  description: API for handling blog operations (CRUD) with role-based access control.
  title: Blog Management API
  version: "1.0"
paths:
  /blogs:
    get:
      description: Retrieves all blog posts from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/blog.Blog'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all blog posts
      tags:
      - Blog
  /blogs/create:
    post:
      consumes:
      - application/json
      description: Allows a writer to create a new blog post
      parameters:
      - description: Blog Post
        in: body
        name: blog
        required: true
        schema:
          $ref: '#/definitions/blog.Blog'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new blog post
      tags:
      - Blog
  /blogs/delete:
    delete:
      description: Allows a writer to delete their blog post
      parameters:
      - description: Blog ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a blog post
      tags:
      - Blog
  /blogs/update:
    put:
      consumes:
      - application/json
      description: Allows a writer to update their blog post
      parameters:
      - description: Updated Blog Post
        in: body
        name: blog
        required: true
        schema:
          $ref: '#/definitions/blog.Blog'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a blog post
      tags:
      - Blog
swagger: "2.0"
